### ISSUE TITLE
F*** your profanity

### ISSUE THREAD

**Issue by neelkamath** [AshtrayShetty/Profanity-Sir-Cuss#1]
I noticed your README (congrats on making one!) said that you couldn't find data on curse words in lyrics. I've come across several in the past, such as [this one](http://lab.musixmatch.com/profanity_genres/). I might've misunderstood the topic, but otherwise maybe it'd help with ideas if you're still working on this.

**Comment by AshrayShetty4** [comment]
My bad. What I meant by that was that I didn't find any apt dataset (As a sort of a proof) which someone could use to get to those conclusions. I hope you understand what I meant now.

**Comment by neelkamath** [comment]
I'm still not sure what you mean, but it's fine either way.
